// Burushaski Digital Archive Combined Data
const dictionaryData = [
  {
    "id": "01",
    "word": "kholtu",
    "meaning": "today",
    "start_seconds": 8,
    "end_seconds": 14.5,
    "audio_file": "01_kholtu_today.mp3",
    "video_file": "01_kholtu_today.mp4",
    "play_bounds": {
      "start": 0.6,
      "end": 1.23
    },
    "pos": "adverb",
    "urdu": "آج",
    "kashmiri": "اَز",
    "kash_ipa": "/az/",
    "bur_perso_srinagar": "کھولتُو",
    "bur_ipa_srinagar": "/kʰolt̪u/",
    "example_srinagar": "Je kholtu bazaarer neyba.",
    "example_en_srinagar": "I am not going to the market today.",
    "bur_perso_gilgit": "کھولتُو",
    "bur_ipa_gilgit": "/kʰolt̪u/",
    "example_gilgit": "Khulto haralt shuqulo.",
    "example_en_gilgit": "It is raining today."
  },
  {
    "id": "02",
    "word": "tsordi",
    "meaning": "tomorrow",
    "start_seconds": 15,
    "end_seconds": 18,
    "audio_file": "02_tsordi_tomorrow.mp3",
    "video_file": "02_tsordi_tomorrow.mp4",
    "play_bounds": {
      "start": 0.2,
      "end": 0.84
    },
    "pos": "adverb",
    "urdu": "کل",
    "kashmiri": "پگاہ",
    "kash_ipa": "/pagaːh/",
    "bur_perso_srinagar": "ثوردی",
    "bur_ipa_srinagar": "/t͡sord̪i/",
    "example_srinagar": "Je tsordi bazaarer nibaa.",
    "example_en_srinagar": "I will go to the market tomorrow.",
    "bur_perso_gilgit": "ثوردی",
    "bur_ipa_gilgit": "/t͡sord̪i/",
    "example_gilgit": "Jimaly ju.",
    "example_en_gilgit": "Come tomorrow."
  },
  {
    "id": "03",
    "word": "ha",
    "meaning": "house",
    "start_seconds": 18,
    "end_seconds": 21,
    "audio_file": "03_ha_house.mp3",
    "video_file": "03_ha_house.mp4",
    "play_bounds": {
      "start": 0.6,
      "end": 0.9
    },
    "pos": "noun",
    "urdu": "گھر",
    "kashmiri": "گَرٕ",
    "kash_ipa": "/garɨ/",
    "bur_perso_srinagar": "ہا",
    "bur_ipa_srinagar": "/ha/",
    "example_srinagar": "A-ha Hari Parbat-ulo bila.",
    "example_en_srinagar": "My house is in Hari Parbat.",
    "bur_perso_gilgit": "ہا",
    "bur_ipa_gilgit": "/ha/",
    "example_gilgit": "Mulgim ha.",
    "example_en_gilgit": "Black house."
  },
  {
    "id": "04",
    "word": "hing",
    "meaning": "door",
    "start_seconds": 21,
    "end_seconds": 23,
    "audio_file": "04_hing_door.mp3",
    "video_file": "04_hing_door.mp4",
    "play_bounds": {
      "start": 0.45,
      "end": 0.83
    },
    "pos": "noun",
    "urdu": "دروازہ",
    "kashmiri": "دَروازہ",
    "kash_ipa": "/darvaːzɨ/",
    "bur_perso_srinagar": "ہِنگ",
    "bur_ipa_srinagar": "/hiŋ/",
    "example_srinagar": "Hing yuwash.",
    "example_en_srinagar": "Open the door.",
    "bur_perso_gilgit": "ہِنگ",
    "bur_ipa_gilgit": "/hiŋ/",
    "example_gilgit": "Hing yuwash.",
    "example_en_gilgit": "Open the door."
  },
  {
    "id": "05",
    "word": "gatung",
    "meaning": "clothes",
    "start_seconds": 23,
    "end_seconds": 25.5,
    "audio_file": "05_gatung_clothes.mp3",
    "video_file": "05_gatung_clothes.mp4",
    "play_bounds": {
      "start": 0.4,
      "end": 0.97
    },
    "pos": "noun",
    "urdu": "کپڑا / پوشاک",
    "kashmiri": "پلو",
    "kash_ipa": "/palav/",
    "bur_perso_srinagar": "گٹُونگ",
    "bur_ipa_srinagar": "/gat̪uŋ/",
    "example_srinagar": "Dasin gane gatung gitsam.",
    "example_en_srinagar": "I bought clothes for the girl.",
    "bur_perso_gilgit": "گٹُونگ",
    "bur_ipa_gilgit": "/gat̪uŋ/",
    "example_gilgit": "Bardum gatung.",
    "example_en_gilgit": "Red clothes."
  },
  {
    "id": "06",
    "word": "lap_chil",
    "meaning": "tea",
    "start_seconds": 25.5,
    "end_seconds": 28.5,
    "audio_file": "06_lap_chil_tea.mp3",
    "video_file": "06_lap_chil_tea.mp4",
    "play_bounds": {
      "start": 0.85,
      "end": 1.65
    },
    "pos": "noun",
    "urdu": "چائے",
    "kashmiri": "چائے",
    "kash_ipa": "/t͡ʃaːj/",
    "bur_perso_srinagar": "لاپ چل",
    "bur_ipa_srinagar": "/lap t͡ʃil/",
    "example_srinagar": "Lap chil mi.",
    "example_en_srinagar": "Drink tea.",
    "bur_perso_gilgit": "لاپ زیل",
    "bur_ipa_gilgit": "/lap ziːl/",
    "example_gilgit": "Lap zil mi.",
    "example_en_gilgit": "Drink tea."
  },
  {
    "id": "07",
    "word": "shapik",
    "meaning": "food",
    "start_seconds": 29,
    "end_seconds": 31.5,
    "audio_file": "07_shapik_food.mp3",
    "video_file": "07_shapik_food.mp4",
    "play_bounds": {
      "start": 0.75,
      "end": 1.23
    },
    "pos": "noun",
    "urdu": "کھانا",
    "kashmiri": "ژوoٹ",
    "kash_ipa": "/t͡soːt/",
    "bur_perso_srinagar": "شپِک",
    "bur_ipa_srinagar": "/ʃapik/",
    "example_srinagar": "Shapik shi.",
    "example_en_srinagar": "Eat the food.",
    "bur_perso_gilgit": "شبِیک",
    "bur_ipa_gilgit": "/ʃabiːk/",
    "example_gilgit": "Shabik shi.",
    "example_en_gilgit": "Eat the food."
  },
  {
    "id": "08",
    "word": "gahr",
    "meaning": "marriage",
    "start_seconds": 32,
    "end_seconds": 34,
    "audio_file": "08_gahr_marriage.mp3",
    "video_file": "08_gahr_marriage.mp4",
    "play_bounds": {
      "start": 0.15,
      "end": 0.66
    },
    "pos": "noun",
    "urdu": "شادی",
    "kashmiri": "کھانٛدر",
    "kash_ipa": "/kʰaːndar/",
    "bur_perso_srinagar": "گہر",
    "bur_ipa_srinagar": "/gaːr/",
    "example_srinagar": "Ine gahr bila.",
    "example_en_srinagar": "It is his marriage.",
    "bur_perso_gilgit": "گر",
    "bur_ipa_gilgit": "/gaːr/",
    "example_gilgit": "Ine gar bila.",
    "example_en_gilgit": "It is his marriage."
  },
  {
    "id": "09",
    "word": "thala",
    "meaning": "slow",
    "start_seconds": 34,
    "end_seconds": 36.5,
    "audio_file": "09_thala_slow.mp3",
    "video_file": "09_thala_slow.mp4",
    "play_bounds": {
      "start": 1.1,
      "end": 1.61
    },
    "pos": "adjective",
    "urdu": "آہستہ",
    "kashmiri": "سُست",
    "kash_ipa": "/sust/",
    "bur_perso_srinagar": "تھلا",
    "bur_ipa_srinagar": "/tʰala/",
    "example_srinagar": "Thala gucchar.",
    "example_en_srinagar": "Walk slowly.",
    "bur_perso_gilgit": "تھلا",
    "bur_ipa_gilgit": "/tʰala/",
    "example_gilgit": "Thala gucchar.",
    "example_en_gilgit": "Walk slowly."
  },
  {
    "id": "10",
    "word": "daghanum",
    "meaning": "fat",
    "start_seconds": 37,
    "end_seconds": 40,
    "audio_file": "10_daghanum_fat.mp3",
    "video_file": "10_daghanum_fat.mp4",
    "play_bounds": {
      "start": 0.95,
      "end": 1.62
    },
    "pos": "adjective",
    "urdu": "موٹا",
    "kashmiri": "وِیوٚٹھ",
    "kash_ipa": "/vjoʈʰ/",
    "bur_perso_srinagar": "دغَنُم",
    "bur_ipa_srinagar": "/d̪aɣanum/",
    "example_srinagar": "Daghanum hir.",
    "example_en_srinagar": "A fat man.",
    "bur_perso_gilgit": "دغَنُم",
    "bur_ipa_gilgit": "/d̪aɣanum/",
    "example_gilgit": "Daghanum hir.",
    "example_en_gilgit": "A fat man."
  },
  {
    "id": "11",
    "word": "beenum",
    "meaning": "thin",
    "start_seconds": 40,
    "end_seconds": 42.5,
    "audio_file": "11_beenum_thin.mp3",
    "video_file": "11_beenum_thin.mp4",
    "play_bounds": {
      "start": 0.8,
      "end": 1.45
    },
    "pos": "adjective",
    "urdu": "پتلا",
    "kashmiri": "تُنک",
    "kash_ipa": "/tunk/",
    "bur_perso_srinagar": "بینُم",
    "bur_ipa_srinagar": "/beːnum/",
    "example_srinagar": "Beenum dasin.",
    "example_en_srinagar": "A thin girl.",
    "bur_perso_gilgit": "بَینُم",
    "bur_ipa_gilgit": "/beːnum/",
    "example_gilgit": "Bainum dasin.",
    "example_en_gilgit": "A thin girl."
  },
  {
    "id": "12",
    "word": "chhagorum",
    "meaning": "cold",
    "start_seconds": 43,
    "end_seconds": 45.5,
    "audio_file": "12_chhagorum_cold.mp3",
    "video_file": "12_chhagorum_cold.mp4",
    "play_bounds": {
      "start": 0.48,
      "end": 1.11
    },
    "pos": "adjective",
    "urdu": "ٹھنڈا",
    "kashmiri": "یَکھ",
    "kash_ipa": "/jakʰ/",
    "bur_perso_srinagar": "چھگورُم",
    "bur_ipa_srinagar": "/t͡ʃʰagorum/",
    "example_srinagar": "Chil chhagorum bila.",
    "example_en_srinagar": "The water is cold.",
    "bur_perso_gilgit": "چھغورُم",
    "bur_ipa_gilgit": "/t͡ʃʰagorum/",
    "example_gilgit": "Chil chaghorum bila.",
    "example_en_gilgit": "The water is cold."
  },
  {
    "id": "13",
    "word": "bayu",
    "meaning": "salt",
    "start_seconds": 46,
    "end_seconds": 48,
    "audio_file": "13_bayu_salt.mp3",
    "video_file": "13_bayu_salt.mp4",
    "play_bounds": {
      "start": 0.8,
      "end": 1.35
    },
    "pos": "noun",
    "urdu": "نمک",
    "kashmiri": "نوٗن",
    "kash_ipa": "/nuːn/",
    "bur_perso_srinagar": "بایو",
    "bur_ipa_srinagar": "/baju/",
    "example_srinagar": "Bayu doro bila.",
    "example_en_srinagar": "The salt is hard.",
    "bur_perso_gilgit": "بیوُ",
    "bur_ipa_gilgit": "/baju/",
    "example_gilgit": "Bayu doro bila.",
    "example_en_gilgit": "The salt is hard."
  },
  {
    "id": "14",
    "word": "kasharum",
    "meaning": "sweet",
    "start_seconds": 48,
    "end_seconds": 51,
    "audio_file": "14_kasharum_sweet.mp3",
    "video_file": "14_kasharum_sweet.mp4",
    "play_bounds": {
      "start": 0.75,
      "end": 1.44
    },
    "pos": "adjective",
    "urdu": "میٹھا",
    "kashmiri": "موٚدُر",
    "kash_ipa": "/modur/",
    "bur_perso_srinagar": "کاشرُم",
    "bur_ipa_srinagar": "/kaʃarum/",
    "example_srinagar": "Balt kasharum bila.",
    "example_en_srinagar": "The apple is sweet.",
    "bur_perso_gilgit": "گشنرم",
    "bur_ipa_gilgit": "/kaʃarum/",
    "example_gilgit": "Balt gashnarum bila.",
    "example_en_gilgit": "The apple is sweet."
  },
  {
    "id": "15",
    "word": "dukoil",
    "meaning": "listen",
    "start_seconds": 51,
    "end_seconds": 54.5,
    "audio_file": "15_dukoil_listen.mp3",
    "video_file": "15_dukoil_listen.mp4",
    "play_bounds": {
      "start": 0.7,
      "end": 1.74
    },
    "pos": "verb",
    "urdu": "سنو",
    "kashmiri": "بوزُن",
    "kash_ipa": "/boːzun/",
    "bur_perso_srinagar": "دُکوئیل",
    "bur_ipa_srinagar": "/d̪ukoil/",
    "example_srinagar": "A-dumo, dukoil!",
    "example_en_srinagar": "O girl, listen!",
    "bur_perso_gilgit": "دُکوئیل",
    "bur_ipa_gilgit": "/d̪ukoil/",
    "example_gilgit": "A-dumo, dukoil!",
    "example_en_gilgit": "O girl, listen!"
  },
  {
    "id": "16",
    "word": "roo",
    "meaning": "come",
    "start_seconds": 55,
    "end_seconds": 57,
    "audio_file": "16_roo_come.mp3",
    "video_file": "16_roo_come.mp4",
    "play_bounds": {
      "start": 0.3,
      "end": 0.79
    },
    "pos": "verb",
    "urdu": "آؤ",
    "kashmiri": "یُن",
    "kash_ipa": "/jun/",
    "bur_perso_srinagar": "رُو",
    "bur_ipa_srinagar": "/ruː/",
    "example_srinagar": "Khole roo!",
    "example_en_srinagar": "Come here!",
    "bur_perso_gilgit": "رُو",
    "bur_ipa_gilgit": "/ruː/",
    "example_gilgit": "Khole ru!",
    "example_en_gilgit": "Come here!"
  },
  {
    "id": "17",
    "word": "ney",
    "meaning": "go",
    "start_seconds": 61,
    "end_seconds": 63.5,
    "audio_file": "17_ney_go.mp3",
    "video_file": "17_ney_go.mp4",
    "play_bounds": {
      "start": 0.7,
      "end": 1.09
    },
    "pos": "verb",
    "urdu": "جاؤ",
    "kashmiri": "گَژھُن",
    "kash_ipa": "/gat͡sʰun/",
    "bur_perso_srinagar": "نے",
    "bur_ipa_srinagar": "/ne/",
    "example_srinagar": "Bazaarer ney!",
    "example_en_srinagar": "Go to the market!",
    "bur_perso_gilgit": "مِ",
    "bur_ipa_gilgit": "/mi/",
    "example_gilgit": "Bazaarer mi!",
    "example_en_gilgit": "Go to the market!"
  },
  {
    "id": "18",
    "word": "shuwa",
    "meaning": "good",
    "start_seconds": 63.5,
    "end_seconds": 66.5,
    "audio_file": "18_shuwa_good.mp3",
    "video_file": "18_shuwa_good.mp4",
    "play_bounds": {
      "start": 0.35,
      "end": 0.86
    },
    "pos": "adjective",
    "urdu": "اچھا",
    "kashmiri": "جان",
    "kash_ipa": "/d͡ʒaːn/",
    "bur_perso_srinagar": "شوا",
    "bur_ipa_srinagar": "/ʃuwa/",
    "example_srinagar": "Shuwa ba.",
    "example_en_srinagar": "I am good.",
    "bur_perso_gilgit": "شُوا",
    "bur_ipa_gilgit": "/ʃuwa/",
    "example_gilgit": "Shuwa ba.",
    "example_en_gilgit": "I am good."
  },
  {
    "id": "19",
    "word": "dalkash",
    "meaning": "very_good",
    "start_seconds": 67,
    "end_seconds": 70,
    "audio_file": "19_dalkash_very_good.mp3",
    "video_file": "19_dalkash_very_good.mp4",
    "play_bounds": {
      "start": 0.6,
      "end": 1.31
    },
    "pos": "adjective",
    "urdu": "بہت اچھا",
    "kashmiri": "واریاہ جان",
    "kash_ipa": "/vaːrjaːh d͡ʒaːn/",
    "bur_perso_srinagar": "دلکَش",
    "bur_ipa_srinagar": "/d̪alkaʃ/",
    "example_srinagar": "Ine dalkash bai.",
    "example_en_srinagar": "He is very good.",
    "bur_perso_gilgit": "دلتَس",
    "bur_ipa_gilgit": "/d̪altas/",
    "example_gilgit": "Ine daltas bai.",
    "example_en_gilgit": "He is very good."
  },
  {
    "id": "20",
    "word": "shukum",
    "meaning": "beautiful",
    "start_seconds": 70,
    "end_seconds": 73.5,
    "audio_file": "20_shukum_beautiful.mp3",
    "video_file": "20_shukum_beautiful.mp4",
    "play_bounds": {
      "start": 0.1,
      "end": 0.67
    },
    "pos": "adjective",
    "urdu": "خوبصورت",
    "kashmiri": "خوٗبصوٗرت",
    "kash_ipa": "/xuːbsuːrat/",
    "bur_perso_srinagar": "شُکُم",
    "bur_ipa_srinagar": "/ʃukum/",
    "example_srinagar": "Dasin shukum bo.",
    "example_en_srinagar": "The girl is beautiful.",
    "bur_perso_gilgit": "شُکُم",
    "bur_ipa_gilgit": "/ʃukum/",
    "example_gilgit": "Dasin shukum bo.",
    "example_en_gilgit": "The girl is beautiful."
  },
  {
    "id": "21",
    "word": "tum",
    "meaning": "tree",
    "start_seconds": 74,
    "end_seconds": 76.5,
    "audio_file": "21_tum_tree.mp3",
    "video_file": "21_tum_tree.mp4",
    "play_bounds": {
      "start": 0.18,
      "end": 0.56
    },
    "pos": "noun",
    "urdu": "درخت",
    "kashmiri": "کُل",
    "kash_ipa": "/kul/",
    "bur_perso_srinagar": "ٹوم",
    "bur_ipa_srinagar": "/t̪om/",
    "example_srinagar": "Tom eikhan bila.",
    "example_en_srinagar": "The tree is tall.",
    "bur_perso_gilgit": "تُم",
    "bur_ipa_gilgit": "/t̪um/",
    "example_gilgit": "Tum eikhan bila.",
    "example_en_gilgit": "The tree is tall."
  },
  {
    "id": "22",
    "word": "giram",
    "meaning": "neighborhood",
    "start_seconds": 77,
    "end_seconds": 80,
    "audio_file": "22_giram_neighborhood.mp3",
    "video_file": "22_giram_neighborhood.mp4",
    "play_bounds": {
      "start": 0.45,
      "end": 1.02
    },
    "pos": "noun",
    "urdu": "محلہ",
    "kashmiri": "مَحلہٕ",
    "kash_ipa": "/mahla/",
    "bur_perso_srinagar": "گِرم",
    "bur_ipa_srinagar": "/giram/",
    "example_srinagar": "Giram-ulo.",
    "example_en_srinagar": "In the neighborhood.",
    "bur_perso_gilgit": "گِرم",
    "bur_ipa_gilgit": "/giram/",
    "example_gilgit": "Giram-ulo.",
    "example_en_gilgit": "In the neighborhood."
  },
  {
    "id": "23",
    "word": "birdi",
    "meaning": "earth",
    "start_seconds": 80,
    "end_seconds": 82.5,
    "audio_file": "23_birdi_earth.mp3",
    "video_file": "23_birdi_earth.mp4",
    "play_bounds": {
      "start": 0.55,
      "end": 1.24
    },
    "pos": "noun",
    "urdu": "زمین",
    "kashmiri": "زٔمیٖن",
    "kash_ipa": "/zəmiːn/",
    "bur_perso_srinagar": "بِردِ",
    "bur_ipa_srinagar": "/bird̪i/",
    "example_srinagar": "Birdi-ulo.",
    "example_en_srinagar": "On the earth.",
    "bur_perso_gilgit": "بِردِ",
    "bur_ipa_gilgit": "/bird̪i/",
    "example_gilgit": "Birdi-ulo.",
    "example_en_gilgit": "On the earth."
  },
  {
    "id": "24",
    "word": "ayash",
    "meaning": "sky",
    "start_seconds": 83,
    "end_seconds": 85,
    "audio_file": "24_ayash_sky.mp3",
    "video_file": "24_ayash_sky.mp4",
    "play_bounds": {
      "start": 0.02,
      "end": 0.56
    },
    "pos": "noun",
    "urdu": "آسمان",
    "kashmiri": "آسمان",
    "kash_ipa": "/aːsmaːn/",
    "bur_perso_srinagar": "اَیَش",
    "bur_ipa_srinagar": "/ajaʃ/",
    "example_srinagar": "Ayash yater bila.",
    "example_en_srinagar": "The sky is above.",
    "bur_perso_gilgit": "اَیَش",
    "bur_ipa_gilgit": "/ajaʃ/",
    "example_gilgit": "Ayash yater bila.",
    "example_en_gilgit": "The sky is above."
  },
  {
    "id": "25",
    "word": "thanum",
    "meaning": "tall_big",
    "start_seconds": 85,
    "end_seconds": 88,
    "audio_file": "25_thanum_tall_big.mp3",
    "video_file": "25_thanum_tall_big.mp4",
    "play_bounds": {
      "start": 0.65,
      "end": 1.15
    },
    "pos": "adjective",
    "urdu": "لمبا",
    "kashmiri": "تھود",
    "kash_ipa": "/tʰod/",
    "bur_perso_srinagar": "تھانُم",
    "bur_ipa_srinagar": "/tʰanum/",
    "example_srinagar": "Thanum tom.",
    "example_en_srinagar": "A tall tree.",
    "bur_perso_gilgit": "غُسنُم / تھانُم",
    "bur_ipa_gilgit": "/tʰanum/",
    "example_gilgit": "Thanum / ghusnum tom.",
    "example_en_gilgit": "A tall / long tree."
  },
  {
    "id": "26",
    "word": "ghusnum",
    "meaning": "long_tall",
    "start_seconds": 88,
    "end_seconds": 91.5,
    "audio_file": "26_ghusnum_long_tall.mp3",
    "video_file": "26_ghusnum_long_tall.mp4",
    "play_bounds": {
      "start": 0,
      "end": 0.46
    },
    "pos": "adjective",
    "urdu": "لمبا",
    "kashmiri": "جیوٹھ",
    "kash_ipa": "/d͡ʒjuːʈʰ/",
    "bur_perso_srinagar": "غُسنُم",
    "bur_ipa_srinagar": "/ɣusnum/",
    "example_srinagar": "Ghusnum ghuying.",
    "example_en_srinagar": "Long hair.",
    "bur_perso_gilgit": "غُسنُم",
    "bur_ipa_gilgit": "/ɣusnum/",
    "example_gilgit": "Ghusnum ghuying.",
    "example_en_gilgit": "Long hair."
  },
  {
    "id": "27",
    "word": "meedum",
    "meaning": "our_body",
    "start_seconds": 92,
    "end_seconds": 95.5,
    "audio_file": "27_meedum_our_body.mp3",
    "video_file": "27_meedum_our_body.mp4",
    "play_bounds": {
      "start": 0.75,
      "end": 1.33
    },
    "pos": "noun",
    "urdu": "ہمارا جسم",
    "kashmiri": "میون جِسم",
    "kash_ipa": "/mjoːn d͡ʒism/",
    "bur_perso_srinagar": "مِیڈِم",
    "bur_ipa_srinagar": "/miːd̪um/",
    "example_srinagar": "Meedum daltas bila.",
    "example_en_srinagar": "Our body is beautiful.",
    "bur_perso_gilgit": "مِیڈِم",
    "bur_ipa_gilgit": "/miːd̪um/",
    "example_gilgit": "Midim daltas bila.",
    "example_en_gilgit": "Our body is beautiful."
  },
  {
    "id": "28",
    "word": "uiras",
    "meaning": "to_die",
    "start_seconds": 96,
    "end_seconds": 98.5,
    "audio_file": "28_uiras_to_die.mp3",
    "video_file": "28_uiras_to_die.mp4",
    "play_bounds": {
      "start": 0.55,
      "end": 1.18
    },
    "pos": "verb",
    "urdu": "مرنا",
    "kashmiri": "مَرُن",
    "kash_ipa": "/marun/",
    "bur_perso_srinagar": "ویرَس",
    "bur_ipa_srinagar": "/uiras/",
    "example_srinagar": "Ine uirabai.",
    "example_en_srinagar": "He is dying.",
    "bur_perso_gilgit": "اویَس",
    "bur_ipa_gilgit": "/uiras/",
    "example_gilgit": "Ine uyasbai.",
    "example_en_gilgit": "He is dying."
  },
  {
    "id": "29",
    "word": "mey",
    "meaning": "we",
    "start_seconds": 99,
    "end_seconds": 101,
    "audio_file": "29_mey_we.mp3",
    "video_file": "29_mey_we.mp4",
    "play_bounds": {
      "start": 0.15,
      "end": 0.56
    },
    "pos": "pronoun",
    "urdu": "ہم",
    "kashmiri": "أسۍ",
    "kash_ipa": "/əsʲ/",
    "bur_perso_srinagar": "مے",
    "bur_ipa_srinagar": "/me/",
    "example_srinagar": "Mey burusho ba.",
    "example_en_srinagar": "We are Burusho.",
    "bur_perso_gilgit": "مِ",
    "bur_ipa_gilgit": "/mi/",
    "example_gilgit": "Mi burusho ba.",
    "example_en_gilgit": "We are Burusho."
  },
  {
    "id": "30",
    "word": "um",
    "meaning": "you",
    "start_seconds": 101,
    "end_seconds": 104.5,
    "audio_file": "30_um_you.mp3",
    "video_file": "30_um_you.mp4",
    "play_bounds": {
      "start": 0.7,
      "end": 1.16
    },
    "pos": "pronoun",
    "urdu": "تم",
    "kashmiri": "ژٕ",
    "kash_ipa": "/t͡sɨ/",
    "bur_perso_srinagar": "اُم",
    "bur_ipa_srinagar": "/um/",
    "example_srinagar": "Um be hal be?",
    "example_en_srinagar": "How are you?",
    "bur_perso_gilgit": "اُم",
    "bur_ipa_gilgit": "/um/",
    "example_gilgit": "Um be hal be?",
    "example_en_gilgit": "How are you?"
  },
  {
    "id": "31",
    "word": "jey",
    "meaning": "me",
    "start_seconds": 105,
    "end_seconds": 108,
    "audio_file": "31_jey_me.mp3",
    "video_file": "31_jey_me.mp4",
    "play_bounds": {
      "start": 0.55,
      "end": 1.03
    },
    "pos": "pronoun",
    "urdu": "میں",
    "kashmiri": "بٔ",
    "kash_ipa": "/bɨ/",
    "bur_perso_srinagar": "جے",
    "bur_ipa_srinagar": "/d͡ʒe/",
    "example_srinagar": "Jey Burusho ba.",
    "example_en_srinagar": "I am a Burusho.",
    "bur_perso_gilgit": "جے",
    "bur_ipa_gilgit": "/d͡ʒe/",
    "example_gilgit": "Je Burusho ba.",
    "example_en_gilgit": "I am a Burusho."
  },
  {
    "id": "32",
    "word": "giretas",
    "meaning": "play",
    "start_seconds": 109,
    "end_seconds": 112,
    "audio_file": "32_giretas_play.mp3",
    "video_file": "32_giretas_play.mp4",
    "play_bounds": {
      "start": 0.85,
      "end": 1.65
    },
    "pos": "verb",
    "urdu": "کھیلنا",
    "kashmiri": "گِنٛدون",
    "kash_ipa": "/gindun/",
    "bur_perso_srinagar": "گیرِیتَس",
    "bur_ipa_srinagar": "/giret̪as/",
    "example_srinagar": "Gushingants giretas.",
    "example_en_srinagar": "The women are dancing.",
    "bur_perso_gilgit": "گیرِیتَس",
    "bur_ipa_gilgit": "/giret̪as/",
    "example_gilgit": "Gushingants giritas.",
    "example_en_gilgit": "The women are dancing."
  },
  {
    "id": "33",
    "word": "urutas",
    "meaning": "sit",
    "start_seconds": 112,
    "end_seconds": 115.5,
    "audio_file": "33_urutas_sit.mp3",
    "video_file": "33_urutas_sit.mp4",
    "play_bounds": {
      "start": 1.2,
      "end": 1.75
    },
    "pos": "verb",
    "urdu": "بیٹھنا",
    "kashmiri": "بِہُن",
    "kash_ipa": "/bihun/",
    "bur_perso_srinagar": "ہُروٹَس",
    "bur_ipa_srinagar": "/urut̪as/",
    "example_srinagar": "Kursi-ulo urutas.",
    "example_en_srinagar": "Sit on the chair.",
    "bur_perso_gilgit": "ہُروٹَس",
    "bur_ipa_gilgit": "/urut̪as/",
    "example_gilgit": "Kursi-ulo hurutas.",
    "example_en_gilgit": "Sit on the chair."
  },
  {
    "id": "34",
    "word": "gartas",
    "meaning": "run",
    "start_seconds": 116,
    "end_seconds": 122.5,
    "audio_file": "34_gartas_run.mp3",
    "video_file": "34_gartas_run.mp4",
    "play_bounds": {
      "start": 1.1,
      "end": 1.9
    },
    "pos": "verb",
    "urdu": "دوڑنا",
    "kashmiri": "دًوُرُن",
    "kash_ipa": "/doːrun/",
    "bur_perso_srinagar": "گارتَس",
    "bur_ipa_srinagar": "/gart̪as/",
    "example_srinagar": "Hiles gartas nibai.",
    "example_en_srinagar": "The boy is running.",
    "bur_perso_gilgit": "گارچَس",
    "bur_ipa_gilgit": "/garchas/",
    "example_gilgit": "Hiles garchas nibai.",
    "example_en_gilgit": "The boy is running."
  },
  {
    "id": "35",
    "word": "demilas",
    "meaning": "hear",
    "start_seconds": 123,
    "end_seconds": 126,
    "audio_file": "35_demilas_hear.mp3",
    "video_file": "35_demilas_hear.mp4",
    "play_bounds": {
      "start": 0.55,
      "end": 1.43
    },
    "pos": "verb",
    "urdu": "سننا",
    "kashmiri": "بوزُن",
    "kash_ipa": "/boːzun/",
    "bur_perso_srinagar": "دِمیلَس",
    "bur_ipa_srinagar": "/d̪emilas/",
    "example_srinagar": "Demilas.",
    "example_en_srinagar": "To hear / listen.",
    "bur_perso_gilgit": "اِمیلَس",
    "bur_ipa_gilgit": "/imilas/",
    "example_gilgit": "Imilas.",
    "example_en_gilgit": "To hear / listen."
  },
  {
    "id": "36",
    "word": "niyas",
    "meaning": "go_verb",
    "start_seconds": 126,
    "end_seconds": 128.5,
    "audio_file": "36_niyas_go_verb.mp3",
    "video_file": "36_niyas_go_verb.mp4",
    "play_bounds": {
      "start": 0.85,
      "end": 1.55
    },
    "pos": "verb",
    "urdu": "جانا",
    "kashmiri": "گَژھُن",
    "kash_ipa": "/gat͡sʰun/",
    "bur_perso_srinagar": "نِیَس",
    "bur_ipa_srinagar": "/nijas/",
    "example_srinagar": "Je bazaarer niyas.",
    "example_en_srinagar": "To go to the market.",
    "bur_perso_gilgit": "نِیَس",
    "bur_ipa_gilgit": "/nijas/",
    "example_gilgit": "Je bazaarer niyas.",
    "example_en_gilgit": "To go to the market."
  },
  {
    "id": "37",
    "word": "piti",
    "meaning": "bread",
    "start_seconds": 129,
    "end_seconds": 133,
    "audio_file": "37_piti_bread.mp3",
    "video_file": "37_piti_bread.mp4",
    "play_bounds": {
      "start": 0.1,
      "end": 0.6
    },
    "pos": "noun",
    "urdu": "روٹی",
    "kashmiri": "ژوoٹ",
    "kash_ipa": "/t͡soːt/",
    "bur_perso_srinagar": "پیٹی",
    "bur_ipa_srinagar": "/pit̪i/",
    "example_srinagar": "Piti shi.",
    "example_en_srinagar": "Eat bread.",
    "bur_perso_gilgit": "فٹِ",
    "bur_ipa_gilgit": "/pit̪i/",
    "example_gilgit": "Phiti shi.",
    "example_en_gilgit": "Eat bread."
  },
  {
    "id": "38",
    "word": "bayu",
    "meaning": "salt",
    "start_seconds": 6,
    "end_seconds": 9,
    "audio_file": "38_bayu_salt.mp3",
    "video_file": "38_bayu_salt.mp4",
    "play_bounds": {
      "start": 0.15,
      "end": 0.73
    },
    "pos": "noun",
    "urdu": "نمک",
    "kashmiri": "نوٗن",
    "kash_ipa": "/nuːn/",
    "bur_perso_srinagar": "بایو",
    "bur_ipa_srinagar": "/baju/",
    "example_srinagar": "Bayu doro bila.",
    "example_en_srinagar": "The salt is hard.",
    "bur_perso_gilgit": "bayu",
    "bur_ipa_gilgit": "",
    "example_gilgit": "",
    "example_en_gilgit": ""
  },
  {
    "id": "39",
    "word": "hoi",
    "meaning": "curry",
    "start_seconds": 9,
    "end_seconds": 11,
    "audio_file": "39_hoi_curry.mp3",
    "video_file": "39_hoi_curry.mp4",
    "play_bounds": {
      "start": 0.02,
      "end": 0.4
    },
    "pos": "noun",
    "urdu": "سبزی / سالن",
    "kashmiri": "ساق",
    "kash_ipa": "/saːk/",
    "bur_perso_srinagar": "ہوی",
    "bur_ipa_srinagar": "/hoi/",
    "example_srinagar": "Hoi shi.",
    "example_en_srinagar": "Eat the curry.",
    "bur_perso_gilgit": "hoi",
    "bur_ipa_gilgit": "",
    "example_gilgit": "",
    "example_en_gilgit": ""
  },
  {
    "id": "40",
    "word": "bua",
    "meaning": "cow",
    "start_seconds": 11,
    "end_seconds": 14,
    "audio_file": "40_bua_cow.mp3",
    "video_file": "40_bua_cow.mp4",
    "play_bounds": {
      "start": 0.28,
      "end": 0.79
    },
    "pos": "noun",
    "urdu": "گائے",
    "kashmiri": "گاو",
    "kash_ipa": "/gaːv/",
    "bur_perso_srinagar": "بُوا",
    "bur_ipa_srinagar": "/bua/",
    "example_srinagar": "Bua bila.",
    "example_en_srinagar": "It is a cow.",
    "bur_perso_gilgit": "bua",
    "bur_ipa_gilgit": "",
    "example_gilgit": "",
    "example_en_gilgit": ""
  },
  {
    "id": "41",
    "word": "haghur",
    "meaning": "horse",
    "start_seconds": 14,
    "end_seconds": 17.5,
    "audio_file": "41_haghur_horse.mp3",
    "video_file": "41_haghur_horse.mp4",
    "play_bounds": {
      "start": 0.55,
      "end": 1.04
    },
    "pos": "noun",
    "urdu": "گھوڑا",
    "kashmiri": "گُر",
    "kash_ipa": "/gur/",
    "bur_perso_srinagar": "ہاغُر",
    "bur_ipa_srinagar": "/haɣur/",
    "example_srinagar": "Haghur gartas nibai.",
    "example_en_srinagar": "The horse is running.",
    "bur_perso_gilgit": "haghur",
    "bur_ipa_gilgit": "",
    "example_gilgit": "",
    "example_en_gilgit": ""
  },
  {
    "id": "42",
    "word": "kantai",
    "meaning": "kite_eagle",
    "start_seconds": 18,
    "end_seconds": 20,
    "audio_file": "42_kantai_kite_eagle.mp3",
    "video_file": "42_kantai_kite_eagle.mp4",
    "play_bounds": {
      "start": 0,
      "end": 0.52
    },
    "pos": "noun",
    "urdu": "چیل / عقاب",
    "kashmiri": "ہِہل",
    "kash_ipa": "/hiːl/",
    "bur_perso_srinagar": "کانتَئی",
    "bur_ipa_srinagar": "/kant̪ai/",
    "example_srinagar": "Kantai ayash-ulo bila.",
    "example_en_srinagar": "The eagle is in the sky.",
    "bur_perso_gilgit": "kantai",
    "bur_ipa_gilgit": "",
    "example_gilgit": "",
    "example_en_gilgit": ""
  },
  {
    "id": "43",
    "word": "hir",
    "meaning": "man",
    "start_seconds": 20,
    "end_seconds": 23.5,
    "audio_file": "43_hir_man.mp3",
    "video_file": "43_hir_man.mp4",
    "play_bounds": {
      "start": 0.7,
      "end": 1.06
    },
    "pos": "noun",
    "urdu": "مرد",
    "kashmiri": "مَرٕد",
    "kash_ipa": "/marɨd/",
    "bur_perso_srinagar": "ہیر",
    "bur_ipa_srinagar": "/hir/",
    "example_srinagar": "Daghanum hir.",
    "example_en_srinagar": "A fat man.",
    "bur_perso_gilgit": "hir",
    "bur_ipa_gilgit": "",
    "example_gilgit": "",
    "example_en_gilgit": ""
  },
  {
    "id": "44",
    "word": "hilas",
    "meaning": "boy_son",
    "start_seconds": 24,
    "end_seconds": 27.5,
    "audio_file": "44_hilas_boy_son.mp3",
    "video_file": "44_hilas_boy_son.mp4",
    "play_bounds": {
      "start": 0.65,
      "end": 1.16
    },
    "pos": "noun",
    "urdu": "لڑکا / بیٹا",
    "kashmiri": "نٚچوٗ",
    "kash_ipa": "/nət͡ʃuː/",
    "bur_perso_srinagar": "ہِلاس",
    "bur_ipa_srinagar": "/hilas/",
    "example_srinagar": "Hiles gartas nibai.",
    "example_en_srinagar": "The boy is running.",
    "bur_perso_gilgit": "hilas",
    "bur_ipa_gilgit": "",
    "example_gilgit": "",
    "example_en_gilgit": ""
  },
  {
    "id": "45",
    "word": "dasin",
    "meaning": "girl_daughter",
    "start_seconds": 28,
    "end_seconds": 31.5,
    "audio_file": "45_dasin_girl_daughter.mp3",
    "video_file": "45_dasin_girl_daughter.mp4",
    "play_bounds": {
      "start": 0.38,
      "end": 1.02
    },
    "pos": "noun",
    "urdu": "لڑکی / بیٹی",
    "kashmiri": "کوٗر",
    "kash_ipa": "/kuːr/",
    "bur_perso_srinagar": "داسِن",
    "bur_ipa_srinagar": "/d̪asin/",
    "example_srinagar": "Dasin shukum bo.",
    "example_en_srinagar": "The girl is beautiful.",
    "bur_perso_gilgit": "dasin",
    "bur_ipa_gilgit": "",
    "example_gilgit": "",
    "example_en_gilgit": ""
  },
  {
    "id": "46",
    "word": "jut",
    "meaning": "small",
    "start_seconds": 32,
    "end_seconds": 34.5,
    "audio_file": "46_jut_small.mp3",
    "video_file": "46_jut_small.mp4",
    "play_bounds": {
      "start": 0.6,
      "end": 1
    },
    "pos": "adjective",
    "urdu": "چھوٹا",
    "kashmiri": "لوکُٹ",
    "kash_ipa": "/lokut/",
    "bur_perso_srinagar": "جُٹ",
    "bur_ipa_srinagar": "/d͡ʒut̪/",
    "example_srinagar": "Jut hiles.",
    "example_en_srinagar": "A small boy.",
    "bur_perso_gilgit": "jut",
    "bur_ipa_gilgit": "",
    "example_gilgit": "",
    "example_en_gilgit": ""
  },
  {
    "id": "47",
    "word": "uyum",
    "meaning": "big",
    "start_seconds": 35,
    "end_seconds": 37.5,
    "audio_file": "47_uyum_big.mp3",
    "video_file": "47_uyum_big.mp4",
    "play_bounds": {
      "start": 0.1,
      "end": 0.6
    },
    "pos": "adjective",
    "urdu": "بڑا",
    "kashmiri": "بوڈ",
    "kash_ipa": "/boːɖ/",
    "bur_perso_srinagar": "اُیُم",
    "bur_ipa_srinagar": "/ujum/",
    "example_srinagar": "Uyum tom.",
    "example_en_srinagar": "A big tree.",
    "bur_perso_gilgit": "uyum",
    "bur_ipa_gilgit": "",
    "example_gilgit": "",
    "example_en_gilgit": ""
  },
  {
    "id": "48",
    "word": "huk",
    "meaning": "dog",
    "start_seconds": 38,
    "end_seconds": 40,
    "audio_file": "48_huk_dog.mp3",
    "video_file": "48_huk_dog.mp4",
    "play_bounds": {
      "start": 0,
      "end": 0.3
    },
    "pos": "noun",
    "urdu": "کتا",
    "kashmiri": "ہوٗن",
    "kash_ipa": "/huːn/",
    "bur_perso_srinagar": "ہُک",
    "bur_ipa_srinagar": "/huk/",
    "example_srinagar": "Huk roo!",
    "example_en_srinagar": "Come, dog!",
    "bur_perso_gilgit": "huk",
    "bur_ipa_gilgit": "",
    "example_gilgit": "",
    "example_en_gilgit": ""
  },
  {
    "id": "49",
    "word": "ja",
    "meaning": "my_mine",
    "start_seconds": 40.5,
    "end_seconds": 43,
    "audio_file": "49_ja_my_mine.mp3",
    "video_file": "49_ja_my_mine.mp4",
    "play_bounds": {
      "start": 0.2,
      "end": 0.77
    },
    "pos": "pronoun",
    "urdu": "میرا",
    "kashmiri": "میوٗن",
    "kash_ipa": "/mjoːn/",
    "bur_perso_srinagar": "جا",
    "bur_ipa_srinagar": "/d͡ʒa/",
    "example_srinagar": "Ja ha.",
    "example_en_srinagar": "My house.",
    "bur_perso_gilgit": "ja",
    "bur_ipa_gilgit": "",
    "example_gilgit": "",
    "example_en_gilgit": ""
  },
  {
    "id": "50",
    "word": "ume",
    "meaning": "your_yours",
    "start_seconds": 43,
    "end_seconds": 46,
    "audio_file": "50_ume_your_yours.mp3",
    "video_file": "50_ume_your_yours.mp4",
    "play_bounds": {
      "start": 0,
      "end": 0.45
    },
    "pos": "pronoun",
    "urdu": "تیرا",
    "kashmiri": "چیوٗن",
    "kash_ipa": "/t͡ʃjoːn/",
    "bur_perso_srinagar": "اُمے",
    "bur_ipa_srinagar": "/ume/",
    "example_srinagar": "Ume tom.",
    "example_en_srinagar": "Your tree.",
    "bur_perso_gilgit": "ume",
    "bur_ipa_gilgit": "",
    "example_gilgit": "",
    "example_en_gilgit": ""
  },
  {
    "id": "51",
    "word": "mi",
    "meaning": "our",
    "start_seconds": 46.5,
    "end_seconds": 51.5,
    "audio_file": "51_mi_our.mp3",
    "video_file": "51_mi_our.mp4",
    "play_bounds": {
      "start": 0.55,
      "end": 1.03
    },
    "pos": "pronoun",
    "urdu": "ہمارا",
    "kashmiri": "سوٗن",
    "kash_ipa": "/suːn/",
    "bur_perso_srinagar": "مِ",
    "bur_ipa_srinagar": "/mi/",
    "example_srinagar": "Mi meedum.",
    "example_en_srinagar": "Our body.",
    "bur_perso_gilgit": "mi",
    "bur_ipa_gilgit": "",
    "example_gilgit": "",
    "example_en_gilgit": ""
  },
  {
    "id": "52",
    "word": "ine",
    "meaning": "his_her",
    "start_seconds": 52,
    "end_seconds": 54,
    "audio_file": "52_ine_his_her.mp3",
    "video_file": "52_ine_his_her.mp4",
    "play_bounds": {
      "start": 0.15,
      "end": 0.66
    },
    "pos": "pronoun",
    "urdu": "اس کا",
    "kashmiri": "تٔسُنٛد",
    "kash_ipa": "/təsuːnd/",
    "bur_perso_srinagar": "اِنے",
    "bur_ipa_srinagar": "/ine/",
    "example_srinagar": "Ine gahr bila.",
    "example_en_srinagar": "It is his marriage.",
    "bur_perso_gilgit": "ine",
    "bur_ipa_gilgit": "",
    "example_gilgit": "",
    "example_en_gilgit": ""
  },
  {
    "id": "53",
    "word": "chhor",
    "meaning": "quickly",
    "start_seconds": 54,
    "end_seconds": 56,
    "audio_file": "53_chhor_quickly.mp3",
    "video_file": "53_chhor_quickly.mp4",
    "play_bounds": {
      "start": 0,
      "end": 0.58
    },
    "pos": "adverb",
    "urdu": "جلدی",
    "kashmiri": "جَلدی",
    "kash_ipa": "/d͡ʒaldi/",
    "bur_perso_srinagar": "چھور",
    "bur_ipa_srinagar": "/t͡ʃʰor/",
    "example_srinagar": "Chhor roo!",
    "example_en_srinagar": "Come quickly!",
    "bur_perso_gilgit": "chhor",
    "bur_ipa_gilgit": "",
    "example_gilgit": "",
    "example_en_gilgit": ""
  },
  {
    "id": "54",
    "word": "but",
    "meaning": "much_more",
    "start_seconds": 56.5,
    "end_seconds": 59,
    "audio_file": "54_but_much_more.mp3",
    "video_file": "54_but_much_more.mp4",
    "play_bounds": {
      "start": 0,
      "end": 0.45
    },
    "pos": "adverb",
    "urdu": "بہت",
    "kashmiri": "واریاہ",
    "kash_ipa": "/vaːrjaːh/",
    "bur_perso_srinagar": "بُٹ",
    "bur_ipa_srinagar": "/but̪/",
    "example_srinagar": "But shuwa.",
    "example_en_srinagar": "Very good.",
    "bur_perso_gilgit": "but",
    "bur_ipa_gilgit": "",
    "example_gilgit": "",
    "example_en_gilgit": ""
  },
  {
    "id": "55",
    "word": "falis",
    "meaning": "less_few",
    "start_seconds": 59.5,
    "end_seconds": 62,
    "audio_file": "55_falis_less_few.mp3",
    "video_file": "55_falis_less_few.mp4",
    "play_bounds": {
      "start": 0.05,
      "end": 0.56
    },
    "pos": "adverb",
    "urdu": "کم",
    "kashmiri": "کَم",
    "kash_ipa": "/kam/",
    "bur_perso_srinagar": "فالِس",
    "bur_ipa_srinagar": "/falis/",
    "example_srinagar": "Falis bayu.",
    "example_en_srinagar": "Less salt.",
    "bur_perso_gilgit": "falis",
    "bur_ipa_gilgit": "",
    "example_gilgit": "",
    "example_en_gilgit": ""
  },
  {
    "id": "56",
    "word": "gati",
    "meaning": "together",
    "start_seconds": 62,
    "end_seconds": 65,
    "audio_file": "56_gati_together.mp3",
    "video_file": "56_gati_together.mp4",
    "play_bounds": {
      "start": 0.58,
      "end": 1.08
    },
    "pos": "adverb",
    "urdu": "اکٹھے / جمع",
    "kashmiri": "اِکتھٕ",
    "kash_ipa": "/iktʰɨ/",
    "bur_perso_srinagar": "گتی",
    "bur_ipa_srinagar": "/gat̪i/",
    "example_srinagar": "Gati urutas.",
    "example_en_srinagar": "Sit together.",
    "bur_perso_gilgit": "gati",
    "bur_ipa_gilgit": "",
    "example_gilgit": "",
    "example_en_gilgit": ""
  },
  {
    "id": "57",
    "word": "mimo",
    "meaning": "own",
    "start_seconds": 65,
    "end_seconds": 67.5,
    "audio_file": "57_mimo_own.mp3",
    "video_file": "57_mimo_own.mp4",
    "play_bounds": {
      "start": 0.35,
      "end": 0.98
    },
    "pos": "pronoun",
    "urdu": "اپنا",
    "kashmiri": "پَنُن",
    "kash_ipa": "/panun/",
    "bur_perso_srinagar": "مِمو",
    "bur_ipa_srinagar": "/mimo/",
    "example_srinagar": "Mimo ha.",
    "example_en_srinagar": "Own house.",
    "bur_perso_gilgit": "mimo",
    "bur_ipa_gilgit": "",
    "example_gilgit": "",
    "example_en_gilgit": ""
  },
  {
    "id": "58",
    "word": "bisin",
    "meaning": "what",
    "start_seconds": 68,
    "end_seconds": 70,
    "audio_file": "58_bisin_what.mp3",
    "video_file": "58_bisin_what.mp4",
    "play_bounds": {
      "start": 0.15,
      "end": 0.67
    },
    "pos": "pronoun",
    "urdu": "کیا",
    "kashmiri": "کیاہ",
    "kash_ipa": "/kjaːh/",
    "bur_perso_srinagar": "بِسِن",
    "bur_ipa_srinagar": "/bisin/",
    "example_srinagar": "Bisin bila?",
    "example_en_srinagar": "What is it?",
    "bur_perso_gilgit": "bisin",
    "bur_ipa_gilgit": "",
    "example_gilgit": "",
    "example_en_gilgit": ""
  },
  {
    "id": "59",
    "word": "awa",
    "meaning": "yes",
    "start_seconds": 70,
    "end_seconds": 73,
    "audio_file": "59_awa_yes.mp3",
    "video_file": "59_awa_yes.mp4",
    "play_bounds": {
      "start": 0.42,
      "end": 0.88
    },
    "pos": "adverb",
    "urdu": "ہاں",
    "kashmiri": "اَنہہ",
    "kash_ipa": "/anhɨ/",
    "bur_perso_srinagar": "اَوا",
    "bur_ipa_srinagar": "/awa/",
    "example_srinagar": "Awa, je Burusho ba.",
    "example_en_srinagar": "Yes, I am Burusho.",
    "bur_perso_gilgit": "awa",
    "bur_ipa_gilgit": "",
    "example_gilgit": "",
    "example_en_gilgit": ""
  },
  {
    "id": "60",
    "word": "bey",
    "meaning": "no",
    "start_seconds": 73,
    "end_seconds": 75.5,
    "audio_file": "60_bey_no.mp3",
    "video_file": "60_bey_no.mp4",
    "play_bounds": {
      "start": 0,
      "end": 0.35
    },
    "pos": "adverb",
    "urdu": "نہیں",
    "kashmiri": "نہہ",
    "kash_ipa": "/nəh/",
    "bur_perso_srinagar": "بے",
    "bur_ipa_srinagar": "/be/",
    "example_srinagar": "Bey, je neyba.",
    "example_en_srinagar": "No, I am not going.",
    "bur_perso_gilgit": "bey",
    "bur_ipa_gilgit": "",
    "example_gilgit": "",
    "example_en_gilgit": ""
  },
  {
    "id": "61",
    "word": "jare",
    "meaning": "to_me",
    "start_seconds": 76,
    "end_seconds": 78.5,
    "audio_file": "61_jare_to_me.mp3",
    "video_file": "61_jare_to_me.mp4",
    "play_bounds": {
      "start": 0.36,
      "end": 1.01
    },
    "pos": "pronoun",
    "urdu": "میرے لیے",
    "kashmiri": "مےٚ خٲطرٕ",
    "kash_ipa": "/meː xaːtˤrɨ/",
    "bur_perso_srinagar": "جارے",
    "bur_ipa_srinagar": "/d͡ʒare/",
    "example_srinagar": "Jare chil duwa.",
    "example_en_srinagar": "Water for me.",
    "bur_perso_gilgit": "jare",
    "bur_ipa_gilgit": "",
    "example_gilgit": "",
    "example_en_gilgit": ""
  },
  {
    "id": "62",
    "word": "chhumo",
    "meaning": "fish",
    "start_seconds": 79,
    "end_seconds": 81.5,
    "audio_file": "62_chhumo_fish.mp3",
    "video_file": "62_chhumo_fish.mp4",
    "play_bounds": {
      "start": 0.35,
      "end": 0.81
    },
    "pos": "noun",
    "urdu": "مچھلی",
    "kashmiri": "گاڈ",
    "kash_ipa": "/gaːɖ/",
    "bur_perso_srinagar": "چھُمو",
    "bur_ipa_srinagar": "/t͡ʃʰumo/",
    "example_srinagar": "Chhumo shi.",
    "example_en_srinagar": "Eat fish.",
    "bur_perso_gilgit": "chhumo",
    "bur_ipa_gilgit": "",
    "example_gilgit": "",
    "example_en_gilgit": ""
  },
  {
    "id": "63",
    "word": "phash",
    "meaning": "finished_end",
    "start_seconds": 82,
    "end_seconds": 85,
    "audio_file": "63_phash_finished_end.mp3",
    "video_file": "63_phash_finished_end.mp4",
    "play_bounds": {
      "start": 0.1,
      "end": 0.49
    },
    "pos": "adjective",
    "urdu": "ختم",
    "kashmiri": "خَتم",
    "kash_ipa": "/xatam/",
    "bur_perso_srinagar": "پھاش",
    "bur_ipa_srinagar": "/pʰaʃ/",
    "example_srinagar": "Doro phash bila.",
    "example_en_srinagar": "The work is finished.",
    "bur_perso_gilgit": "phash",
    "bur_ipa_gilgit": "",
    "example_gilgit": "",
    "example_en_gilgit": ""
  }
];

const audioArchiveData = [
  {
    "id": "arch_01",
    "title": "An Intelligent Old Man",
    "filename": "Burushaski story An Intellegent Old Man.mp3",
    "category": "folktale",
    "genre": "Folk Story / Oral History",
    "duration": "2:13",
    "collector": "Community Oral Traditions",
    "description": "An oral recording of a traditional Burushaski folktale highlighting the wisdom of an old man in resolving community conflicts and family affairs. This recording provides rich insights into colloquial speech structures, vocabulary relating to kinship and elders, and traditional moral frameworks.",
    "keywords": [
      "Folklore",
      "Hunza Valley",
      "Oral History",
      "Kinship",
      "Wisdom"
    ],
    "transcript": [
      { "time": "01:30 - 01:35", "text": "Because this farmer's name is foreign," },
      { "time": "01:35 - 01:41", "text": "who has lived in Timeline in different countries," },
      { "time": "01:41 - 01:44", "text": "all around the edges of the spectrum" },
      { "time": "01:45 - 01:46", "text": "and its fall looks like this." },
      { "time": "01:49 - 01:50", "text": "What about this farmer," },
      { "time": "02:20 - 02:23", "text": "Jariyukh lillahi sabadi." },
      { "time": "02:23 - 02:25", "text": "Nusen, in Wazirabad," },
      { "time": "02:25 - 02:26", "text": "Awaw Nusenin," },
      { "time": "02:26 - 02:29", "text": "Nimitai Mafe Lillahi." },
      { "time": "02:29 - 02:35", "text": "Mafe Lillahi Mgin Tambai Nusenin." },
      { "time": "02:35 - 02:37", "text": "Min shwa sizan," },
      { "time": "02:37 - 02:39", "text": "Shwa Gaga Daunu Velvam." },
      { "time": "02:39 - 02:44", "text": "Nusenin Shwa Zilmei Mizut. Ile," },
      { "time": "02:44 - 02:46", "text": "Iyakal banas rake," },
      { "time": "02:46 - 02:48", "text": "Tameinu Juatimu." },
      { "time": "02:48 - 02:50", "text": "Juatas rake mafe Lillahi," },
      { "time": "02:50 - 02:55", "text": "Jiufar Rajimu. Nuh," },
      { "time": "02:55 - 02:56", "text": "Bakar Kar," },
      { "time": "02:56 - 02:57", "text": "Hai Rah dakar Zimu," },
      { "time": "02:57 - 02:58", "text": "dakar Zu," },
      { "time": "02:58 - 03:00", "text": "Ima Dau," },
      { "time": "03:00 - 03:02", "text": "Dak Giri." },
      { "time": "03:04 - 03:09", "text": "Tameinu dakar zimu, Lemafe," },
      { "time": "03:09 - 03:11", "text": "Uma Kot Tum Aishif raga," },
      { "time": "03:11 - 03:13", "text": "dakar vidamu," },
      { "time": "03:13 - 03:15", "text": "budgag aishif raga." },
      { "time": "03:15 - 03:16", "text": "Uma Jara sena," },
      { "time": "03:16 - 03:19", "text": "Ko Ke Tum Aishinu Negin." },
      { "time": "03:19 - 03:20", "text": "Ese Bishal," },
      { "time": "03:20 - 03:23", "text": "ese ve Phalo leemi," },
      { "time": "03:23 - 03:27", "text": "Ese mehrad veyar mehmi," },
      { "time": "03:27 - 03:29", "text": "Uma Shishruma," },
      { "time": "03:31 - 03:33", "text": "Uma Gui Akhora Nu me," },
      { "time": "03:33 - 03:35", "text": "Uma Dar Kalti Bhi," },
      { "time": "03:37 - 03:39", "text": "Bud Ajata Guma Nu Ka?" },
      { "time": "03:39 - 03:41", "text": "Uma Dila," },
      { "time": "03:42 - 03:44", "text": "Ki Ume Se Pharushma," },
      { "time": "03:44 - 03:46", "text": "Se lemge Nu me," },
      { "time": "03:46 - 03:48", "text": "Bafaira Pharasanmi," },
      { "time": "03:50 - 03:52", "text": "Yajumar Bishan Jara Dila," },
      { "time": "03:52 - 03:54", "text": "Jaa Tum Bakta Bakta Hara sanse." },
      { "time": "03:54 - 03:56", "text": "Se Le Sva Ke," },
      { "time": "03:56 - 03:58", "text": "Tameinu Senu Mijamre Rabiya," },
      { "time": "03:58 - 04:00", "text": "Jaya Kut Maa Kut Bhushraye," },
      { "time": "04:00 - 04:05", "text": "Jaya Kut Bhushraye Jaya Tamba, Ke," },
      { "time": "04:05 - 04:07", "text": "Jaa Rakul Barderu Naa savaadi." },
      { "time": "04:09 - 04:11", "text": "Jaa Rna Kara Bhushraya," },
      { "time": "04:11 - 04:14", "text": "Agatir Naa Naanu Nimi Ke," },
      { "time": "04:16 - 04:18", "text": "Jaa Kabzin Hai Yam," },
      { "time": "04:18 - 04:20", "text": "Sanas Haa Ke," },
      { "time": "04:20 - 04:22", "text": "Mafaira Sanmi," },
      { "time": "04:22 - 04:24", "text": "yaju Ya Dakul Te Rakim," },
      { "time": "04:24 - 04:26", "text": "Mii Bapata," },
      { "time": "04:26 - 04:28", "text": "Mii Bapatara," },
      { "time": "04:28 - 04:30", "text": "Uma Tameinu Jangayi," },
      { "time": "04:31 - 04:33", "text": "Uma Abzak Tameinu Jangayi," },
      { "time": "04:33 - 04:36", "text": "Ke Ase Reh Uduna Laudu Asman," },
      { "time": "04:36 - 04:39", "text": "Maa Ase Pharum Yushima," },
      { "time": "04:39 - 04:43", "text": "Uu Naa Yapata Rabdi aiyyong," },
      { "time": "04:43 - 04:45", "text": "Ase Pharum," },
      { "time": "04:45 - 04:47", "text": "Ase Mia Wa," },
      { "time": "04:47 - 04:49", "text": "Ase Pharum Yushima," },
      { "time": "04:50 - 04:52", "text": "Manum Ke Naa Ke Jaa Ke Yuja Wa," },
      { "time": "04:52 - 04:54", "text": "Agat Jaa Ushima Manimi," },
      { "time": "04:54 - 04:56", "text": "Jaya Jemu," },
      { "time": "04:56 - 04:58", "text": "Maa Pharisho," },
      { "time": "04:58 - 04:59", "text": "Mii Bapatara Sho," },
      { "time": "04:59 - 05:01", "text": "Uu Mai na Tafal Jash Kiya Ba," },
      { "time": "05:01 - 05:02", "text": "Uu Mai Na Tafala Jash Kiya Ba," },
      { "time": "05:02 - 05:04", "text": "Jaa Mai na Tafala Jaa," },
      { "time": "05:04 - 05:06", "text": "Ao Laa Tashu Truman," },
      { "time": "05:06 - 05:09", "text": "Segun Tam Khosh Nima Nir," },
      { "time": "05:10 - 05:12", "text": "Moor Khosh Nima Nir," },
      { "time": "05:12 - 05:13", "text": "I Nina Reh," },
      { "time": "05:13 - 05:15", "text": "bao an aashar musik," },
      { "time": "05:15 - 05:17", "text": "I Nina Reh Yuom Bhi," },
      { "time": "05:17 - 05:19", "text": "Sana Mai Bapatara," },
      { "time": "05:19 - 05:21", "text": "Uma Kudu Dua Chuva," },
      { "time": "05:21 - 05:22", "text": "Uma Borshu Dua Chuva," },
      { "time": "05:22 - 05:24", "text": "Ke Ke Jayi Kantu Uma Reh," },
      { "time": "05:24 - 05:25", "text": "San Manu Maa," },
      { "time": "05:25 - 05:26", "text": "Maa Hai San Mi," },
      { "time": "05:26 - 05:30", "text": "Jaya Juya Mai Mehrvan, Juya," },
      { "time": "05:31 - 05:33", "text": "Ke anber Gosham," },
      { "time": "05:33 - 05:35", "text": "San Ke," },
      { "time": "05:36 - 05:38", "text": "Tam Se Nima," },
      { "time": "05:38 - 05:40", "text": "Ben Sewa, San," },
      { "time": "05:40 - 05:42", "text": "Seo Se Nima Jaa Ma Pher Joa," },
      { "time": "05:42 - 05:44", "text": "Amil Tumijan Egi Bam Ke," },
      { "time": "05:45 - 05:46", "text": "Ese Palo," },
      { "time": "05:47 - 05:49", "text": "agar mandi wa sivam Ke," },
      { "time": "05:49 - 05:51", "text": "Toh Ram Gathas Pwari Nuhfari," },
      { "time": "05:51 - 05:54", "text": "Eta Gatholu, Kapi," },
      { "time": "05:54 - 05:55", "text": "Mula Tan Nee Nurasa," },
      { "time": "05:55 - 05:57", "text": "Tumijan Pwari Bhiyaman," },
      { "time": "05:57 - 05:58", "text": "Uban Kul Shiman," },
      { "time": "05:59 - 06:00", "text": "Afam Ke Wala Rajiman," },
      { "time": "06:00 - 06:02", "text": "Moor Jaa Tumitai," },
      { "time": "06:02 - 06:03", "text": "Toh Mandira Karo," },
      { "time": "06:03 - 06:05", "text": "Puk Tumijan Mehna Moor Ke," },
      { "time": "06:05 - 06:07", "text": "Jara Egi Dumun Egi Muna," },
      { "time": "06:07 - 06:08", "text": "Palo ai Yam Nusuna," },
      { "time": "06:08 - 06:10", "text": "Yin Yunga Sa Aishra Bhi Mujana," },
      { "time": "06:10 - 06:11", "text": "Aishra Bhi Mujana," },
      { "time": "06:11 - 06:13", "text": "Tam Dakho Shima Nima," },
      { "time": "06:13 - 06:14", "text": "Sam Laba Hai," },
      { "time": "06:14 - 06:15", "text": "moor Shahi Seva," },
      { "time": "06:15 - 06:17", "text": "moor bhiyam Baran Tumusuna," },
      { "time": "06:17 - 06:18", "text": "Dat Ri Gi Yunga Mein," },
      { "time": "06:18 - 06:20", "text": "Yus Ka Ke," },
      { "time": "06:22 - 06:24", "text": "Ese Nyun Juhan Metin," },
      { "time": "06:27 - 06:29", "text": "Tam Ere Gala Bhojan, Dalimi," },
      { "time": "06:29 - 06:31", "text": "Sami Meeru, Tam," },
      { "time": "06:31 - 06:33", "text": "Ooh Tumijan Hai, Yole," },
      { "time": "06:34 - 06:35", "text": "Ghi Wala Ga Toh Nuh," },
      { "time": "06:35 - 06:37", "text": "Hik phalo Bhoji Bhiyam," },
      { "time": "06:38 - 06:39", "text": "Jaa Tumijan," },
      { "time": "06:39 - 06:40", "text": "Joor Kusunui," },
      { "time": "06:40 - 06:41", "text": "Ek Gurunni," },
      { "time": "06:42 - 06:44", "text": "Han Matalui, altar," },
      { "time": "06:44 - 06:45", "text": "phalo joumi," },
      { "time": "06:45 - 06:46", "text": "Sara Sa Ke," },
      { "time": "06:48 - 06:49", "text": "Tam Ere Salimi," },
      { "time": "06:49 - 06:50", "text": "Sali Nadaat bhumi," },
      { "time": "06:50 - 06:52", "text": "Moor Jaa Han Bhai Arbanyan Kasha," },
      { "time": "06:52 - 06:53", "text": "Moor Bhi Nimi," },
      { "time": "06:53 - 06:56", "text": "Jaa Jaya Tan Bhai Arbanyati, Uma," },
      { "time": "06:56 - 06:57", "text": "Tumijan Hai," },
      { "time": "06:57 - 06:59", "text": "Alta Chir, Uma," },
      { "time": "06:59 - 07:00", "text": "Uma Rai Phalo," },
      { "time": "07:01 - 07:01", "text": "Ek Gurunmi," },
      { "time": "07:01 - 07:02", "text": "Rau Mumi," },
      { "time": "07:02 - 07:03", "text": "Kar Nuh Dal," },
      { "time": "07:03 - 07:04", "text": "Thirik nuh nahin," },
      { "time": "07:04 - 07:05", "text": "se Nuh," },
      { "time": "07:05 - 07:06", "text": "Iski Se Lvani Mee," },
      { "time": "07:06 - 07:07", "text": "Ke Moda," },
      { "time": "07:07 - 07:08", "text": "Teh Bar Nahin Di," },
      { "time": "07:08 - 07:09", "text": "Ki Yaar Dal," },
      { "time": "07:09 - 07:10", "text": "Bhoji Bhiyam," },
      { "time": "07:10 - 07:11", "text": "Kota Bhoji Aapu," },
      { "time": "07:11 - 07:12", "text": "Toh Lu," },
      { "time": "07:12 - 07:13", "text": "Amel Junga," },
      { "time": "07:13 - 07:14", "text": "Samar bhoi yam," },
      { "time": "07:14 - 07:15", "text": "Sara Ke," },
      { "time": "07:17 - 07:19", "text": "Mafae Hai, Ine," },
      { "time": "07:22 - 07:23", "text": "Ashrai Bhuski," },
      { "time": "07:23 - 07:24", "text": "Yani Mei Ke," },
      { "time": "07:24 - 07:26", "text": "Ela Nithi Mein Mein, Ina," },
      { "time": "07:26 - 07:28", "text": "Tam Mein, Ine," },
      { "time": "07:28 - 07:29", "text": "Ata Bharatan," },
      { "time": "07:29 - 07:33", "text": "teh shwa shwa Duroi Mein, Duniyaad," },
      { "time": "07:33 - 07:34", "text": "se Mein," },
      { "time": "07:34 - 07:35", "text": "Ame Teh," },
      { "time": "07:35 - 07:37", "text": "Fai Dah, Ine," },
      { "time": "07:38 - 07:40", "text": "Mudha Takhachin, Uyaman," },
      { "time": "07:41 - 07:42", "text": "Ele Nimne Spashpuri." },
      { "time": "07:42 - 07:43", "text": "Thirik Nahin," },
      { "time": "07:43 - 07:44", "text": "Kota Bhoji," },
      { "time": "07:45 - 07:47", "text": "Yani Mein, nahin," }
    ]
  },
  {
    "id": "arch_02",
    "title": "Um Ba Khudaye",
    "filename": "Um Ba Khudaye.mp3",
    "category": "devotional",
    "genre": "Devotional Poetry / Chant",
    "duration": "3:01",
    "collector": "Religious Oral Poetry Corpus",
    "description": "A devotional performance ('Um Ba Khudaye') conveying spiritual themes in Burushaski. This record highlights lyrical structures, intonation, and religious/philosophical lexical items characteristic of devotional oral poetry.",
    "keywords": [
      "Devotional",
      "Poetry",
      "Chant",
      "Spiritual",
      "Lyrical"
    ]
  },
  {
    "id": "arch_03",
    "title": "Folk Song (Standard)",
    "filename": "folk song.mp3",
    "category": "song",
    "genre": "Traditional Folk Song",
    "duration": "6:25",
    "collector": "Traditional Music Recordings",
    "description": "A traditional Burushaski folk song capturing lyrical performance, musicality, and historical/cultural motifs of the Gilgit-Baltistan mountain valleys. It features classical song structure and dialect-specific vowel lengths.",
    "keywords": [
      "Music",
      "Folk Song",
      "Lyrical",
      "Heritage",
      "Hunza"
    ]
  },
  {
    "id": "arch_04",
    "title": "Folk Song (Alternative)",
    "filename": "folk song (2).mp3",
    "category": "song",
    "genre": "Traditional Folk Song",
    "duration": "1:09",
    "collector": "Traditional Music Recordings",
    "description": "An additional traditional Burushaski folk song showing a variation in melody, lyrical composition, and dialectal nuances. Collected to document oral performance variety and melodic themes.",
    "keywords": [
      "Music",
      "Folk Song",
      "Melody",
      "Acoustic",
      "Performance"
    ]
  }
];
